spring.application.name=Event Organiser
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.pmayefcfhbxqbyoufame
spring.datasource.password=vcFqETc150Z1L3Km
spring.datasource.driver-class-name=org.postgresql.Driver
