spring.application.name=Event Organiser
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.pmayefcfhbxqbyoufame
spring.datasource.password=vcFqETc150Z1L3Km
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=raulmarginean1963@gmail.com
spring.mail.properties.mail.smtp.from=raulmarginean1963@gmail.com
spring.mail.password=iopp nnyh hdgn mzpp 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
